version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myresume-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hz2o1edsxucr"
s3_prefix = "myresume-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

